config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'dev' => 'home#dev'

  get 'records' => 'home#records'
  post 'records' => 'home#records'
  post 'export' => 'home#export'

  resources :facilities
  resources :companies
  resources :residents
  resources :employees
  resources :visitors
  resources :appointments
  resources :users
  resources :sessions, only: [ :new, :create, :destroy ]
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company
  has_many :appointments, foreign_key: :visitor_id, as: :visitor
  has_many :hosts, class_name: :Resident, through: :appointments

  before_save do
    name.upcase!
    plate.upcase!
  end

  public def id_with_type
    return self.id.to_s + ?# + self.class.to_s
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  load_and_authorize_resource
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    @companies = Company.all
  end

  # GET /employees/1/edit
  def edit
    @companies = Company.all
  end

  # POST /employees
  # POST /employees.json
  def create
    params = employee_params
    params[:created_by_id] = current_user.id

    @employee = Employee.new(params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Funcionário cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    params = employee_params
    params[:updated_by_id] = current_user.id

    respond_to do |format|
      if @employee.update(params)
        format.html { redirect_to @employee, notice: 'Funcionário atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy

    respond_to do |format|
      if @employee.appointments.empty?
        @employee.destroy
        format.html { redirect_to employees_url, notice: 'Funcionário descadastrado.' }
        format.json { head :no_content }
      else
        flash.now[:alert] = 'Não é possivel apagar um funcionário enquanto ainda houverem visitas cadastradas.'
        format.html { render :show }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:cpf, :name, :company_id, :plate)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.haml
= form_with(model: employee, local: true) do |form|
  - if employee.errors.any?
    #error_explanation
      %h2
        = pluralize(employee.errors.count, "error")
        prohibited this employee from being saved:
      %ul
        - employee.errors.full_messages.each do |message|
          %li= message
  .row
    .col-25
      = form.label :name, 'Nome do funcionário:'
    .col-75
      = form.text_field :name, required: true
  .row
    .col-25
      = form.label :cpf, 'Cpf:'
    .col-75
      = form.text_field :cpf, placeholder: 'XXX.XXX.XXX-XX', id: 'cpf'
  .row
    .col-25
      = form.label :company_id, 'Empresa:'
    .col-75
      = form.collection_select :company_id, @companies, :id, :name, required: true
  .row
    .col-25
      = form.label :plate, 'Placa de Veículo'
    .col-75
      = form.text_field :plate, id: 'plate', placeholder: 'AAA 1A11'
  .row
    = form.submit 'Avançar'

app/views/employees/edit.html.haml
.container
  %h1 Editando Funcionário
  %hr
  = render 'form', employee: @employee
  %p
    = link_to 'Voltar', @employee

app/views/employees/index.html.haml
.container
  %h1 Funcionários
  %hr
  = button_to 'Novo', new_employee_path, method: :get

  - if @employees.empty?
    %p Nada encontrado.
  - else
    %table
      %th Nome:
      %th Cpf:
      %th Empresa:
      - @employees.each do |employee|
        %tr
          %td= link_to employee.name, employee
          %td= employee.cpf
          %td= link_to employee.company.name, employee.company

  %p
    Total:
    = @employees.count

app/views/employees/new.html.haml
.container
  %h1 Novo Funcionário
  %hr
  = render 'form', employee: @employee
  %p
    = link_to 'Voltar', employees_path

app/views/employees/show.html.haml
.container
  %h1
    = @employee.name
    %hr
  .row
    .col-25
      Cpf:
    .col-75
      = @employee.cpf
  .row
    .col-25
      Empresa:
    .col-75
      = link_to @employee.company.name, @employee.company
  .row
    .col-25
      Placa do Veículo:
    .col-75
      = @employee.plate
  .row
    .col-25
      Últimas visitas:
    .col-75
      - if @employee.appointments.empty?
        Nenhuma Visita
      - else
        - @employee.appointments.each do |appointment|
          = link_to appointment.description, appointment
          com
          = link_to appointment.host.name, appointment.host
          em
          = appointment.date
          %br/
  %p
    Criado por
    = link_to @employee.created_by.name, @employee.created_by
    em
    = @employee.created_at
    %br
    - if @employee.updated?
      Atualizado por
      = link_to @employee.updated_by.name, @employee.updated_by
      em
      = @employee.updated_at
  %p
    = link_to 'Editar', edit_employee_path(@employee)
    = link_to 'Apagar', @employee, method: :delete, data: { confirm: 'Esta ação é irreversível. Deseja continuar?' }