config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'dev' => 'home#dev'

  get 'records' => 'home#records'
  post 'records' => 'home#records'
  post 'export' => 'home#export'

  resources :facilities
  resources :companies
  resources :residents
  resources :employees
  resources :visitors
  resources :appointments
  resources :users
  resources :sessions, only: [ :new, :create, :destroy ]
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  has_many :appointments, foreign_key: :visitor_id, as: :visitor
  has_many :hosts, class_name: :Resident, through: :appointments

  before_save do
    name.upcase!
    plate.upcase!
  end

  public def id_with_type
    return self.id.to_s + ?# + self.class.to_s
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  load_and_authorize_resource
  before_action :set_visitor, only: [:show, :edit, :update, :destroy]

  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.all
  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors
  # POST /visitors.json
  def create
    params = visitor_params
    params[:created_by_id] = current_user.id

    @visitor = Visitor.new(params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to @visitor, notice: 'Visitante cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1
  # PATCH/PUT /visitors/1.json
  def update
    params = visitor_params
    params[:updated_by_id] = current_user.id

    respond_to do |format|
      if @visitor.update(params)
        format.html { redirect_to @visitor, notice: 'Visitante atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy

    respond_to do |format|
      if @visitor.appointments.empty?
        @visitor.destroy
        format.html { redirect_to visitors_url, notice: 'Visitante descadastrado.' }
        format.json { head :no_content }
      else
        flash.now[:alert] = 'Não é possivel apagar um visitante enquanto ainda houverem visitas marcadas.'
        format.html { render :show }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visitor_params
      params.require(:visitor).permit(:name, :cpf, :plate)
    end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/_form.html.haml
= form_with(model: visitor, local: true) do |form|
  - if visitor.errors.any?
    #error_explanation
      %h2
        = pluralize(visitor.errors.count, "error")
        prohibited this visitor from being saved:"
      %ul
        - visitor.errors.full_messages.each do |message|
          %li= message
  .row
    .col-25
      = form.label :name, 'Nome do visitante:'
    .col-75
      = form.text_field :name, required: true
  .row
    .col-25
      = form.label :cpf, 'Cpf:'
    .col-75
      = form.text_field :cpf, id: 'cpf', required: true
  .row
    .col-25
      = form.label :plate, 'Placa do Veículo'
    .col-75
      = form.text_field :plate, id: 'plate'
  .row
    = form.submit 'Avançar'

app/views/visitors/edit.html.haml
.container
  %h1 Editando Visitante
  %hr
  = render 'form', visitor: @visitor
  %p
    = link_to 'Voltar', @visitor

app/views/visitors/index.html.haml
.container
  %h1 Visitantes
  %hr
  = button_to 'Novo', new_visitor_path, method: :get

  - if @visitors.empty?
    %p Nada encontrado.
  - else
    %table
      %th Nome
      %th Cpf
      - @visitors.each do |visitor|
        %tr
          %td= link_to visitor.name, visitor
          %td= visitor.cpf

  %p
    Total:
    = @visitors.count

app/views/visitors/new.html.haml
.container
  %h1 Novo visitante
  %hr
  = render 'form', visitor: @visitor
  %p
    = link_to 'Voltar', visitors_path

app/views/visitors/show.html.haml
.container
  %h1
    = @visitor.name
    %hr
  .row
    .col-25
      Cpf:
    .col-75
      = @visitor.cpf
  .row
    .col-25
      Placa do Veículo:
    .col-75
      = @visitor.plate
  .row
    .col-25
      Últimas visitas:
    .col-75
      - if @visitor.appointments.empty?
        Nenhuma visita
      - else
        - @visitor.appointments.each do |appointment|
          = link_to appointment.description, appointment
          com
          = link_to appointment.host.name, appointment.host
          em
          = appointment.date
          %br/
  %p
    Criado por
    = link_to @visitor.created_by.name, @visitor.created_by
    em
    = @visitor.created_at
    %br
    - if @visitor.updated?
      Atualizado por
      = link_to @visitor.updated_by.name, @visitor.updated_by
      em
      = @visitor.updated_at
  %p
    = link_to 'Editar', edit_visitor_path(@visitor)
    = link_to 'Apagar', @visitor, method: :delete, data: { confirm: 'Esta ação é irreversível. Deseja continuar?' }