config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'dev' => 'home#dev'

  get 'records' => 'home#records'
  post 'records' => 'home#records'
  post 'export' => 'home#export'

  resources :facilities
  resources :companies
  resources :residents
  resources :employees
  resources :visitors
  resources :appointments
  resources :users
  resources :sessions, only: [ :new, :create, :destroy ]
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
end

app/controllers/home_controller.rb
require 'cpf_gen'
require "prawn/table"

class HomeController < ApplicationController

  def index

    if params[:purpose] == 'particular'
      @visitors = Visitor.all
    else
      @visitors = Employee.all
    end

    if params[:facility]
      unless params[:facility][:id].empty?
        flash.clear
        params[:facility_id] = params[:facility][:id]
      else
        flash[:alert] = "Escolha um Local."
      end
    end

    if params[:facility_id] #!@facility
      @facility = Facility.find_by(id: params[:facility_id])
    end

    @valid_cpf = CPF.verify params[:cpf] if params[:cpf]

    if !@visitor #and @valid_cpf
      if params[:purpose] == 'particular'
        @visitor = Visitor.find_by( cpf: params[:cpf] )
      else
        @visitor = Employee.find_by(cpf: params[:cpf])
      end

      if !@visitor && params[:name]
        if params[:purpose] == 'particular'
          @visitor = Visitor.new(cpf: params[:cpf], name: params[:name], plate: params[:plate])
        else
          params[:company_id] = params[:company][:id] if params[:company]
          @visitor = Employee.new(cpf: params[:cpf], name: params[:name], company_id: params[:company_id], plate: params[:plate])
        end
      end
    end

    if @visitor
      @appointment = Appointment.new
    end

    if @visitor && @appointment && params[:date] && params[:host]
      @appointment.date = DateTime.parse(params[:date] +'T'+ params[:time])
      @appointment.host_id = params[:host]
      @appointment.description = params[:description]
      @appointment.professional = params[:purpose] == 'professional'
      @appointment.visitor_type = @visitor.class.name
      @appointment.created_by_id = current_user.id

      
      if @visitor.id
        @appointment.visitor_id = @visitor.id
      else
        @visitor.created_by_id = current_user.id
        @visitor.save
	      @appointment.visitor_id = @visitor.id
      end

      if @appointment.save
        redirect_to root_path, notice: 'Visita agendada com sucesso!'
      end
    end
  end

  #   Parameters: {"utf8"=>"✓",
  #               "authenticity_token"=>"HASH",
  #               "filters"=>["facility"],
  #               "facility"=>{"id"=>"1"},
  #               "resident"=>{"id"=>""},
  #               "cpf"=>"",
  #               "commit"=>"Buscar"}
  def records
    # If filter parameters have been set, start the filtering.
    if params[:filters]
      appointments = [ ]

      # If a facility has been filtered, then filter by all residents
      if params[:filters].include? 'facility'
        appointments.concat Facility.find_by_id(params[:facility][:id]).appointments
      end

      # If a host has been selected, add it to the filtering
      if params[:filters].include? 'resident'
        appointments.concat Resident.find_by_id(params[:resident][:id]).appointments
      end

      if params[:filters].include? 'employee'
        appointments.concat Employee.find_by_id( params[:employee][:id] ).appointments
      end

      if params[:filters].include? 'visitor'
        appointments.concat Visitor.find_by_id( params[:visitor][:id] ).appointments
      end

      if params[:filters].include? 'cpf'
        if Employee.exists? cpf: params[:cpf]
          appointments.concat(Employee.find_by(cpf: params[:cpf]).appointments)
        end

        if Visitor.exists? cpf: params[:cpf]
          appointments.concat(Visitor.find_by(cpf: params[:cpf]).appointments)
        end
      end
      
      @appointments = appointments.uniq # might be nil
      puts @appointments

    end
  end

  def export
    puts ?1 * 10
    appointments = params[:appointments]
    #puts appointments

    send_data generate_pdf(appointments),
      filename: "History #{Date.today}.pdf",
              type: "application/pdf"
  end

  def generate_pdf(appointment_ids)
    appointments = Appointment.find appointment_ids
    puts appointments

    data = [ ["Data e Hora", "Visitado", "Visitante", "Motivo"] ]

    Prawn::Document.new do
      text "Histórico de Visitas", align: :center, size: 20
#      text "Data e Hora | Visitado | Visitante | Motivo"
      appointments.each do |a|
        data += [ [a.date.to_s, a.host.name, a.visitor.name, a.description] ]
#        text a.date.to_s + ?| + a.host.name + ?| + a.visitor.name + ?| + a.description
      end
      table data, header: true do
        row(0).font_style = :bold
      end
      string = "Exportado em #{Date.today} às #{Time.now.strftime("%k:%M")}"
      options = { at: [bounds.right - 200, 0],
                  width: 200,
                  align: :right }
      number_pages string, options
    end.render
  end

  def dev
    @facilities = Facility.all
    @companies = Company.all
  end

end

app/helpers/home_helper.rb
module HomeHelper
  def maximum_resident_count( facilities )
    return facilities.max do |f, g|
      f.residents.count <=> g.residents.count
    end.residents.count
  end

  def rows_for_facility( facility )
    return facility.residents.count + facility.residents.sum { |h| h.appointments.count }
  end

  def rows_for_company( company )
    return company.employees.count + company.employees.sum { |e| e.appointments.count }
  end

  def rows_for_resident( resident )
    return resident.appointments.count
  end

  def rows_for_employee( employee )
    return employee.appointments.count
  end

  def rows_for( object )
    return rows_for_facility(object) if object.kind_of? Facility
    return rows_for_company(object) if object.kind_of? Company
    return rows_for_resident(object) if object.kind_of? Resident
    return rows_for_employee(object) if object.kind_of? Employee
  end

  def select name, collection
    collection_select name, :id, collection, :id, :name, include_blank: true
  end
end

app/views/home/_appointment_form.html.haml
.container
  = form_with method: :get, local: true do
    .row
      .col-25= label_tag :host, 'Visitado'
      .col-75b= select_tag :host, options_for_select(@facility.residents.collect{ |h| [h.name, h.id]})
    .container
      .row
        .col-25= label_tag :date, 'Data da Visita:'
        .col-75
          .col-50
            = hidden_field_tag :date, '', id: "my-input", required: true
            .testStyle{id: "my-datepicker"}
        
              //        .col-25= label_tag :time, 'Hora da Visita'

          .col-25R
            = text_field_tag :time, '', id: "my-timepicker", required: true
            = button_tag 'Hora Atual', type: :button, onclick: "getTime('my-timepicker')"
      .row
        .col-25= label_tag :description, 'Descrição:'
        .col-75= text_area_tag :description, '', rows: "3", cols: "60", required: true
    .row
      = hidden_field_tag :facility_id, params[:facility_id]
      = hidden_field_tag :purpose, params[:purpose]
      = hidden_field_tag :cpf, @visitor.cpf
      = hidden_field_tag :name, @visitor.name
      = hidden_field_tag :plate, @visitor.plate
      - if params[:purpose] == 'professional'
        = hidden_field_tag :company_id, params[:company_id]
        = hidden_field_tag :visitor_type, Employee.to_s
      - else
        = hidden_field_tag :visitor_type, Visitor.to_s
      = submit_tag 'Avançar'

:javascript
  function getTime(i) {
    var d = new Date(),
      h = (d.getHours()<10?'0':'') + d.getHours(),
      m = (d.getMinutes()<10?'0':'') + d.getMinutes();
    document.getElementById(i).value = h + ':' + m;
  }

app/views/home/_cpf_validator.html.haml
.container
  = form_with method: :get, local: true do
    .row
      - if @valid_cpf == false
        CPF Inválido! Insira novamente:
    .row
      .col-25
        = label_tag :cpf, 'CPF:'
      .col-75
        = text_field_tag :cpf, params[:cpf], required: true, id: 'cpf'
    .row
      = hidden_field_tag :facility_id, params[:facility_id]
      = hidden_field_tag :purpose, params[:purpose]
      = submit_tag 'Validar'

app/views/home/_facilities.html.haml
.form
  = form_with do
    = hidden_field_tag :source, params[:source]
    .row
      .col-25
        Histórico de Visitas por Prédio:
      .col-75
        = collection_select :facility, :id, Facility.all, :id, :name, required: true, prompt: true
    .row
      .col-75
        = submit_tag 'Próximo'

app/views/home/_history.html.haml
:coffee
  $ '#close'
    .click -> $('#history').slideUp 500

.container
  .float-r= button_tag 'Fechar', id: :close
  .float-l= button_to 'Exportar', export_path, params: {appointments: appointments }
  %p
  - unless appointments
    %p Nenhuma visita foi encontrada!
  - else
    %table
      %th Data e Hora
      %th Visitado
      %th Visitante
      %th Motivo
      - appointments.each do |a|
        %tr
          %td= a.date
          %td= link_to a.host.name, a.host
          %td= link_to a.visitor.name, a.visitor
          %td= a.description
    %p
      Total:
      = appointments.count

app/views/home/_residents.html.haml
.container
  %h1
    Morador:

app/views/home/_visitor_form.html.haml
.container
  = form_with method: :get, local: true do
    .row
      .col-25= label_tag :cpf, 'CPF:'
      .col-75
        - if @visitor
          = text_field_tag :cpf, @visitor.cpf, disabled: true
          = hidden_field_tag :cpf, params[:cpf]
        - else
          = text_field_tag :cpf, params[:cpf], data: { inputmask: "'mask:' '999.999.999-99'" }
    .row
      .col-25= label_tag :name, 'Nome:'
      .col-75
        - if @visitor
          = text_field_tag :name, @visitor.name, disabled: true
          = hidden_field_tag :name, @visitor.name
        - else
          = text_field_tag :name, '',required: true, autofocus: true
    .row
      .col-25= label_tag :plate, 'Placa do Veículo'
      .col-75
        - if @visitor
          = text_field_tag :plate, @visitor.plate, disabled:true
          = hidden_field_tag :plate, @visitor.plate
        - else
          = text_field_tag :plate
    - if params[:purpose] == "professional"
      .row
        .col-25= label_tag :company, 'Empresa:'
        .col-75
          - if @visitor
            = text_field_tag :company, @visitor.company.name, disabled: true
            = hidden_field_tag :company, @visitor.company.name
          - else
            = collection_select :company, :id, Company::all, :id, :name, required: true, prompt: true
    .row
      = hidden_field_tag :facility_id, params[:facility_id]
      = hidden_field_tag :purpose, params[:purpose]
      - if !@visitor
        = submit_tag "Avançar"

app/views/home/_visitors.html.haml
.container
  %h1
    Visitante: 

app/views/home/dev.html.haml
%p
  - if current_user
    Logged as
    = link_to current_user.name, current_user
  - else
    How did you get here without logging in?

%h1 Developer Panel

%h2 Resource Tree
.container
  %table
    %tr
      %td{ rowspan: 3 }= link_to 'Users', users_path
      %td{ rowspan: 3 }= link_to 'Visitors', visitors_path
      %td= link_to 'Facilities', facilities_path
      %td= link_to 'Companies', companies_path
    %tr
      %td= link_to 'Residents', residents_path
      %td= link_to 'Employees', employees_path
    %tr
      %td{ colspan: 2 }= link_to 'Appointments', appointments_path
      
%h2 Database Overview
.container
  %table
    %th Facility
    %th Residents
    %th Appointments
    - @facilities.each do |facility|
      %tr
        %td{ rowspan: rows_for(facility) }= link_to facility.name, facility
        - facility.residents.each do |resident|
          %td{ rowspan: rows_for(resident) }= link_to resident.name, resident
          - resident.appointments.each do |appointment|
            %td
              = link_to appointment.description, appointment
              with
              = link_to appointment.visitor.name, appointment.visitor
              - if appointment.visitor.kind_of? Employee
                from
                = link_to appointment.visitor.company.name, appointment.visitor.company
              - else
                (private)
              at
              = appointment.date
            </tr><tr>
          </tr><tr>
%br
.container
  %table
    %th Company
    %th Employees
    %th Appointments
    - @companies.each do |company|
      %tr
        %td{ rowspan: rows_for(company) }= link_to company.name, company
        - company.employees.each do |employee|
          %td{ rowspan: rows_for(employee) }= link_to employee.name, employee
          - employee.appointments.each do |appointment|
            %td
              = link_to appointment.description, appointment
              to
              = link_to appointment.host.name, appointment.host
              in
              = link_to appointment.host.facility.name, appointment.host.facility
              at
              = appointment.created_at
            </tr><tr>
          </tr><tr>

app/views/home/index.html.haml
.container
  %h1 Nova Visita
  %hr

  = form_with method: :get, local: true do
    - if can? :manage, Company
      .row
        .col-25
          = label_tag :purpose, 'Motivo da Visita:'
        .col-75
          = radio_button_tag :purpose, 'particular', params[:purpose] == 'particular', required: true
          = label :particular, 'Particular', for: :purpose_particular
          = radio_button_tag :purpose, 'professional', params[:purpose] == 'professional'
          = label :professional, 'Profissional (Serviço)', for: :purpose_professional
    - else
      = hidden_field_tag :purpose, 'particular'
    .row
      .col-25
        = label_tag :facility, 'Localidade:'
      .col-75
        = collection_select :facility, :id, Facility::all, :id, :name, required: true, prompt: "Selecione um local."
    .row
      = submit_tag 'Avançar'

// CPF Validator Form
- if params[:facility_id] and params[:purpose] and not @visitor and (not params[:cpf] or not @valid_cpf)
  = render 'cpf_validator'

// Visitor/Employee Form
- if params[:facility_id] and params[:purpose] and params[:cpf] and @valid_cpf
  = render 'visitor_form'

// Appointment Form
- if @visitor
  = render 'appointment_form'

app/views/home/records.html.haml
.container
  %h1 Histórico de Visitas
  %hr

  // Record Filters
  #filters
    .form
      = form_with do
        - filters = 'filters[]' # a little helper
        .row
          .col-25
            = check_box_tag filters, :facility, false, id: :filter_facility
            = label :facility, 'Prédio:', for: :filter_facility
          .col-75
            = select :facility, Facility::all
        .row
          .col-25
            = check_box_tag filters, :resident, false, id: :filter_resident
            = label :resident, 'Morador:', for: :filter_resident
          .col-75
            = select :resident, Resident::all
        .row
          .col-25
            = check_box_tag filters, :employee, false, id: :filter_employee
            = label :employee, 'Funcionário:', for: :filter_employee
          .col-75
            = select :employee, Employee::all
        .row
          .col-25
            = check_box_tag filters, :visitor, false, id: :filter_visitor
            = label :visitor, 'Visitante:', for: :filter_visitor
          .col-75
            = select :visitor, Visitor::all
        .row
          .col-25
            = check_box_tag filters, :cpf, false, id: :filter_cpf
            = label :cpf, 'CPF:', for: :filter_cpf
          .col-75
            = text_field_tag :cpf
        .row
          .col-75  
            = submit_tag 'Buscar', data: { disable_with: 'Buscando...' }

// Records
#history{ style: 'display: none;' }