config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'dev' => 'home#dev'

  get 'records' => 'home#records'
  post 'records' => 'home#records'
  post 'export' => 'home#export'

  resources :facilities
  resources :companies
  resources :residents
  resources :employees
  resources :visitors
  resources :appointments
  resources :users
  resources :sessions, only: [ :new, :create, :destroy ]
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title Gestão de Visitantes
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if current_user
      .float-l
        = link_to 'http://www.asesat.com.br', target: :_blank do
          = image_tag 'logo.png', size: 30

      .float-r
        = link_to 'mailto:fabio@moritzalmeida.eng.br' do
          = image_tag 'email.png', size: 30

        = link_to 'http://www.moritzalmeida.eng.br', target: :_blank do
          = image_tag 'logoMA.png', size: 30

      .container#menu
        - if can? :create, Appointment
          = link_to 'Nova Visita', root_path
          |
        - if current_user.role <= 3
          = link_to 'Histórico', records_path
          |
        - if can? :manage, Facility
          = link_to 'Prédios', facilities_path
          |
        - if can? :manage, Resident
          = link_to 'Moradores', residents_path
          |
        - if can? :manage, Company
          = link_to 'Empresas', companies_path
          |
        - if can? :manage, Employee
          = link_to 'Funcionários', employees_path
          |
        - if can? :manage, Visitor
          = link_to 'Visitantes', visitors_path
          |
        - if can? :manage, Appointment
          = link_to 'Visitas', appointments_path
          |
        - if can? :manage, User
          = link_to 'Usuários', users_path
          |
        = link_to 'Logout', logout_path
    #alert= alert
    #notice= notice
    = yield